### ISSUE TITLE
Fringe of single source vs frequency doesn't match expectations

### ISSUE THREAD

**Issue by dannyjacobs** [HERA-Team/pyuvsim#18]
Simulating a single source off zenith, across a wide bandwith, the phase does not evolve as quickly with frequency as one would expect. By many orders of magnitude.  A units discrepancy in the phase calculation is a leading hypothesis.

Simulation
![image](https://user-images.githubusercontent.com/63191/40459734-ec12ab1e-5eb7-11e8-84d6-c3713c6b310c.png)

With simple model (orange)
![image](https://user-images.githubusercontent.com/63191/40459754-ffee84b4-5eb7-11e8-8163-7663bc4070ae.png)

Plot code:
plot(d.freq_array[0]/1e6,np.angle(d.data_array[0,0,:,0].T))
geometric_delay = 8.14*1e-9
model = np.exp(-1j*2*np.pi*geometric_delay * d.freq_array[0])
ylabel('phs')
xlabel('MHz')
plot(d.freq_array[0]/1e6,np.angle(model))

**Comment by aelanman** [comment]
Machine-precision level difference between phase angles for two simulations. The azimuth angle of the source between these sims differs by 90°.

![phase_diff_off-zenith_changed_az_90d](https://user-images.githubusercontent.com/12849618/40459774-1ac52cfc-5eb8-11e8-96d8-6c1c04a18757.png)

The uvfits files are in /home/alanman/pyuvsim/scripts/off_zenith/.

**Comment by jpober** [comment]
This particular test passes, but the broader tests for sources not just offset east west needed.
