### ISSUE TITLE
Point sources are not points

### ISSUE THREAD

**Issue by jpober** [HERA-Team/pyuvsim#21]
Simulating an array (in this case, MWA) with three point sources gives blobs of flux density.  Things don't quite seem to line up coherently.

<img width="626" alt="screenshot 2018-05-24 16 28 38" src="https://user-images.githubusercontent.com/1482671/40557048-b053f540-6003-11e8-8520-0d4037dffb27.png">

**Comment by dannyjacobs** [comment]
lmns seem to be the same on all baselines
uvws seems to be ok, but the triangle test was only short baselines.  @aelanman will run a triangle baseline test with ~1km baselines
the only other thing in the visibility equation is the beam.  @bhazelton is adding a "tophat" beam object to remove the complexity of the hera beam from the equation

**Comment by bhazelton** [comment]
We tried the tophat beam and saw no improvement. Now we're considering whether it's a problem with pyuvdata's phasing. We're going to try running on the `uvdata_time_array_fix` branch which has better phasing.

**Comment by jpober** [comment]
Fixed.  It was a minus sign in the fringe equation!
