### ISSUE TITLE
RA/Dec orientation

### ISSUE THREAD

**Issue by jpober** [HERA-Team/pyuvsim#36]
Need to input sources in RA/Dec/Epoch, make sure they come out at the right places.

**Comment by dannyjacobs** [comment]
Sources at input RA Decs show up where we expect them to in the image.
Using @aelanman's "HERA" skywriting test and overplotting RA/Decs output as an npz by the run, they seem to match at the resolution of the MWA.

![image](https://user-images.githubusercontent.com/63191/42837636-800ba3c2-89b3-11e8-9da4-48ecb2ad1906.png)



![image](https://user-images.githubusercontent.com/63191/42837518-2a06deb0-89b3-11e8-9c52-d6cff496b316.png)
