### ISSUE TITLE
Test files need new phasing

### ISSUE THREAD

**Issue by jpober** [HERA-Team/pyuvsim#38]
pyuvdata phasing has changed, but our files for unit tests were made with old pyuvdata.  Need to update the files (and/or replace unit tests to use param reader tools)

**Comment by jpober** [comment]
Associated tests currently pass because of high tolerances.  Need to decrease them once the new files are created.

**Comment by jpober** [comment]
Add a w component to one of the tests (long baseline?) to address #34

**Comment by aelanman** [comment]
I've updated all the test files on the branch `update_test_files`. All tests are passing except `test_single_offzenith_source_uvfits`.
This test compares analytic visibility calculation to the calculation from pyuvsim.
